/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MKE02Z64xxx4
package_id: MKE02Z64VLD4
mcu_data: ksdk2_0
processor_version: 24.12.10
pin_labels:
- {pin_num: '26', pin_signal: PTA6/FTM2_FLT1/ACMP1_IN0/ADC0_SE2, label: door}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '29', peripheral: GPIOA, signal: 'GPIO, 28', pin_signal: PTD4/KBI1_P4}
  - {pin_num: '36', peripheral: UART1, signal: TX, pin_signal: PTC7/UART1_TX}
  - {pin_num: '37', peripheral: UART1, signal: RX, pin_signal: PTC6/UART1_RX}
  - {pin_num: '26', peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: PTA6/FTM2_FLT1/ACMP1_IN0/ADC0_SE2, direction: INPUT}
  - {pin_num: '35', peripheral: KBI0, signal: 'P, 0', pin_signal: PTA0/KBI0_P0/FTM0_CH0/ACMP0_IN0/ADC0_SE0, direction: INPUT, pullup_enable: disable}
  - {pin_num: '15', peripheral: GPIOA, signal: 'GPIO, 18', pin_signal: PTC2/FTM2_CH2/ADC0_SE10}
  - {pin_num: '18', peripheral: GPIOA, signal: 'GPIO, 29', pin_signal: PTD5/KBI1_P5}
  - {pin_num: '38', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: PTE2/SPI0_MISO, direction: OUTPUT}
  - {pin_num: '31', peripheral: GPIOA, signal: 'GPIO, 26', pin_signal: PTD2/KBI1_P2/SPI1_MISO, direction: OUTPUT}
  - {pin_num: '1', peripheral: GPIOA, signal: 'GPIO, 25', pin_signal: PTD1/KBI1_P1/FTM2_CH3/SPI1_MOSI}
  - {pin_num: '30', peripheral: GPIOA, signal: 'GPIO, 27', pin_signal: PTD3/KBI1_P3/SPI1_PCS0}
  - {pin_num: '2', peripheral: FTM2, signal: 'CH, 2', pin_signal: PTD0/KBI1_P0/FTM2_CH2/SPI1_SCK, direction: OUTPUT}
  - {pin_num: '40', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: PTE0/SPI0_SCK/FTM1_CLK, direction: OUTPUT, gpio_init_state: 'false', high_drive_enable: enable,
    pullup_enable: enable}
  - {pin_num: '39', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: PTE1/SPI0_MOSI, direction: OUTPUT, gpio_init_state: 'false', high_drive_enable: enable, pullup_enable: enable}
  - {pin_num: '22', peripheral: GPIOA, signal: 'GPIO, 10', pin_signal: PTB2/KBI0_P6/SPI0_SCK/FTM0_CH0/ADC0_SE6, direction: INPUT}
  - {pin_num: '19', peripheral: ADC, signal: 'SE, 9', pin_signal: PTC1/FTM2_CH1/ADC0_SE9}
  - {pin_num: '41', peripheral: GPIOA, signal: 'GPIO, 21', pin_signal: PTC5/FTM1_CH1/RTCO, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{

    gpio_pin_config_t gpioa_pin26_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA6 (pin 26) */
    GPIO_PinInit(kGPIO_PORTA, 6U, &gpioa_pin26_config);

    gpio_pin_config_t gpioa_pin22_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA10 (pin 22) */
    GPIO_PinInit(kGPIO_PORTB, 2U, &gpioa_pin22_config);

    gpio_pin_config_t gpioa_pin41_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA21 (pin 41) */
    GPIO_PinInit(kGPIO_PORTC, 5U, &gpioa_pin41_config);

    gpio_pin_config_t gpioa_pin31_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA26 (pin 31) */
    GPIO_PinInit(kGPIO_PORTD, 2U, &gpioa_pin31_config);

    gpio_pin_config_t gpiob_pin40_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 40) */
    GPIO_PinInit(kGPIO_PORTE, 0U, &gpiob_pin40_config);

    gpio_pin_config_t gpiob_pin39_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 39) */
    GPIO_PinInit(kGPIO_PORTE, 1U, &gpiob_pin39_config);

    gpio_pin_config_t gpiob_pin38_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 38) */
    GPIO_PinInit(kGPIO_PORTE, 2U, &gpiob_pin38_config);
    /* High Current Drive Capability of PTE0: 0x01u */
    PORT_SetHighDriveEnable(PORT, kPORT_HighDrive_PTE0, true);
    /* High Current Drive Capability of PTE1: 0x01u */
    PORT_SetHighDriveEnable(PORT, kPORT_HighDrive_PTE1, true);
    /* Pull Enable for Port E Bit 0: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTE, 0U, true);
    /* Pull Enable for Port E Bit 1: 0x01u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTE, 1U, true);
    /* Pull Enable for Port A Bit 0: 0x00u */
    PORT_SetPinPullUpEnable(PORT, kPORT_PTA, 0U, false);
    /* pin 2 is configured as FTM2_CH2 */
    PORT_SetPinSelect(kPORT_FTM2CH2, kPORT_FTM2_CH2_PTD0);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
